### PR TITLE
Ripemd160

### PR DESCRIPTION
**Pull request by dinosaure**

### CODE REVIEW

**Comment by hannesm** [comment]
I see some issues with this PR:
- there's still some leftovers of the cryptokit (LGPL licensed) code (I'd avoid to integrate the first commit in the history tbh)
- the C implementation you import has a copyright statement with all rights reserved... can't you find a C implementation which is permissively licensed (public domain or BSD* or ISC or sth?)

but that's only me being picky (and I'm not a lawyer, thus don't know much about licenses, only try to stay out of trouble)

**Comment by dinosaure** [comment]
I deleted (in a weird and not useful way) the implementation of the RIPEMD160 from X. L. I keep the current implementation and I broke my git history ...

About the current implementation and your comment @hannesm, I don't know - I'm not a lawyer too but the file has only a copyright (not a license).

**Comment by dinosaure** [comment]
Cleaned the history.

**Comment by dinosaure** [comment]
I asked to Antoon Bosselaers to use this C implementation - if you can find a free licensed implementation, I can change. At this stage, we wait the Antoon's response.

**Comment by hannesm** [comment]
@dinosaure I found https://github.com/ryancdotorg/brainflayer/blob/master/ripemd160_256.c which is public domain.

**Comment by dinosaure** [comment]
👍 I will integrate this code now!

**Comment by dinosaure** [comment]
Integrated 👍 !

**Pull request merged**
