### PR TITLE
BLAKE2S (see #13)

### PR DESCRIPTION
**Pull request by dinosaure**
See #13

### CODE REVIEW

**Comment by cfcs** [comment]
Awesome!!

It looks like the test vectors are missing; here are some links (in various formats):
- https://github.com/pyca/cryptography/pull/2867/files
- https://github.com/BLAKE2/BLAKE2/blob/master/testvectors/blake2s-kat.txt
- https://tools.ietf.org/html/rfc7693#appendix-E

**Comment by dinosaure** [comment]
Interesting test input, I did not see! I will integrate this test in `digestif` 👍 !

**Comment by dinosaure** [comment]
I catched 2 errors:
* one in the C implementation (only for `Bytes` module)
* some in the OCaml implementation

I will fixed its and merge.

**Comment by dinosaure** [comment]
All works. I merge and I will put tests in other PR 👍 !

**Comment by cfcs** [comment]
Are you getting the test cases from the reference implementation?

**Comment by dinosaure** [comment]
Not yet, I will make a new PR to separate the work. But, no worries, I want to integrate your test (and do a benchmark then) before the next release 👍 .

**Pull request merged**
