### PR TITLE
Sha3-512

### PR DESCRIPTION
**Pull request by lyrm**
The C implementation is adapted from [tiny_sha3](https://github.com/mjosaarinen/tiny_sha3). 

The output size is fixed at 512 bits, but should be a parameter. For the C implementation, I am thinking of generating all cases (224, 248, 384 and 512) with macros in `src-c/native/stubs.c`, and for ocaml, with functors (obviously), similarly to what is done for sha384.

### CODE REVIEW

**Comment by dinosaure** [comment]
The linter is not happy but a `dune build @fmt --auto-promote` will fix it.

> The output size is fixed at 512 bits, but should be a parameter. For the C implementation, I am thinking of generating all cases (224, 248, 384 and 512) with macros in src-c/native/stubs.c, and for ocaml, with functors (obviously), similarly to what is done for sha384.

This issue is about naming convention where `SHA{224,256,384,512}` is an implementation of `SHA2`, so should we provide `SHA3_{224,256,384,512}`? (/cc @hannesm @cfcs).

Otherwise, nice job :+1: (#84, /cc @vbmithr).

**Comment by lyrm** [comment]
Hi ! Thanks for the comment. I add sha3_{224, 248, 384} with their tests.

**Comment by dinosaure** [comment]
I think a good plan about naming convention of hash is to keep the current state and at one point deprecate `SHA{224,256,384,512}` and replace it by `SHA2_{224,256,384,512}`.

I did a look about the code and it seems fine for me - but I would like a review from another. Then @lyrm, feel free to fill tests with some others inputs such as `blake2{b,s}` :+1: (such as [this little test](https://github.com/mjosaarinen/tiny_sha3/blob/master/main.c#L46) but don't be afraid to take large inputs from Python or PHP implementation).

**Comment by hannesm** [comment]
some high-level comments (I did not look at this PR in detail, neither do I know digestif in detail):
- I'd appreciate to have the origin of the C source file as a comment in itself
- I can't see any tests for hmac
- I can see some code caring about big and little endian, but I fail to find a CI system for big endian --> does digestif support big endian (if so, I'd appreciate to figure out a CI system for it)
- in the ml implementation, you define Int64.lsr = Int64.shift_right and Int64.asr = Int64.shift_right_logical -- which is counterintuitive after reading [the documentation](http://caml.inria.fr/pub/docs/manual-ocaml/libref/Int64.html#VALshift_right)

**Comment by dinosaure** [comment]
> I can see some code caring about big and little endian, but I fail to find a CI system for big endian --> does digestif support big endian (if so, I'd appreciate to figure out a CI system for it)

I'm not sure to understand the question, by CI, you mean Continuous Integration? Note that this part of `digestif.c` directly comes from `nocrypto`. Then, I'm aware mirage/ocaml-freestanding#74 so we probably can directly use `endian.h`.

**Comment by hannesm** [comment]
@dinosaure my question is: are you aware of a big-endian CI system which could be used in digestif (and other projects), so we can ensure that the conditionally compiled big-endian code actually works?

**Comment by cfcs** [comment]
I agree that `SHA3_*` is a good name, and that `SHA_*` should probably have been called `SHA2_*` from the beginning, but also don't see much point to changing the latter at the moment.

Code looks good, would have appreciated more tests. e.g. the crypto++ project seems to have a bunch: https://github.com/weidai11/cryptopp/commit/01d137155ccbed6045a0ae5eb8eb02cbcaadbdca

Would also be interesting to have randomized tests that verify that the OCaml and C implementations agree on hashes, but that's probably better done in a different PR (and would generally be nice).

@lyrm generally when you have code like `(n / 8)` and you are can guarantee that `n` is always a positive integer, you can get slightly faster code (well that particular instruction will be ~20x faster and play nicer with other threads) by using `(n lsr 3)` instead. The compiler can't perform this optimization for you because it has to consider the case where the integer is negative. But it doesn't look like you have too many divisions/modulo operation in the hot loops, so probably fine here.

**Comment by dinosaure** [comment]
> I can't see any tests for hmac

Some common tests exist about HMAC - but I think the `test.ml` is not easy to read now ...

I updated the OCaml implementation where vector tests highlighted a bug about a _desynchronization_ between the `data` field and the `st` field. In the C implementation both use the same memory area (with `union`) but it was not the case on the OCaml implementation. The trick is more about _bitmasks_  on `int64` but it passes all tests.

Waiting the CI and ready to merge.

**Pull request merged**
