### PR TITLE
Implement #20

### PR DESCRIPTION
**Pull request by dinosaure**
@vbmithr It's good for you ? I provide `MakeBLAKE2B` and `MakeBLAKE2S` which expect a `digest_size` value. I did not implement tests yet but I would like to know if the interface fits good for you.

### CODE REVIEW

**Comment by vbmithr** [comment]
Can you make it so that it does not need a functor instantiation in order to get compute a hash for a certain size? I understand it might break your interfaces as other hashes functions are not variable-size, but as it stands I don't find it particularly elegant to have to instantiate a function in order to specify a hash size.

**Comment by dinosaure** [comment]
I'm not sure if it's a good idea but we could use GADT like:

```ocaml
type t
typer buffer
type _ hash = SHA : t hash | BLAKE2 : (length:int -> t) hash

val digest : 'a hash -> buffer -> 'a
```

in the [module T](https://github.com/mirage/digestif/blob/master/src/digestif_sig.mli#L70) and continue to have functor for the imperative way (with `init`, `feed` and `get`).

**Comment by vbmithr** [comment]
I tried, it is helpful to avoid applying onself the functor, but there is still a functor application under the hood, not awesome :(

**Comment by vbmithr** [comment]
Check it: https://github.com/mirage/digestif/pull/22

**Pull request closed without merging**
