### PR TITLE
add RIPEMD160

### PR DESCRIPTION
**Pull request by vbmithr**

### CODE REVIEW

**Comment by dinosaure** [comment]
I will provide the computation but in OCaml and I will merge it, thanks 👍 !

**Comment by hannesm** [comment]
@dinosaure pls keep in mind cryptokit is LGPL-2 AFAICT, thus merging code from there will taint this repository...  I'd instead go and either develop yourself or find some public domain / MIT code...

**Comment by dinosaure** [comment]
Ah ok, thanks for this notice!

**Comment by vbmithr** [comment]
Or just ask @xavierleroy to relicense this file in ISC.
Otherwise, http://homes.esat.kuleuven.be/~bosselae/ripemd160.html

**Comment by dinosaure** [comment]
I took the A. Bosselaers's implementation and mix with some pre-defined functions of digestif. So, I think, we are good about the license. Then, the OCaml implementation is in the pipe, I will add some tests and push all.

Sorry @vbmithr for the delay but ICFP/CUFP and a little vacation took my time.

**Comment by dinosaure** [comment]
See #12

**Pull request closed without merging**
