### PR TITLE
Make S.t abstract

### PR DESCRIPTION
**Pull request by samoht**

### CODE REVIEW

**Comment by samoht** [comment]
Note: `(x :> string)` can now be done with `H.to_raw_string x`

**Comment by dinosaure** [comment]
I don't have any strong opinion about this PR - and I think it's better to entirely abstract the type `t` - however, I want to know if any people has a really usage of `(x :> string)` (@cfcs?). If not, I will merge it.

**Comment by cfcs** [comment]
What do we gain by making it abstract, and what does the value represent? (Is it a finalized/"valid" hash, or is it some intermediary state)?

**Comment by samoht** [comment]
@cfcs we gain abstraction :-) e.g. it's easier to embed manipulate `Digestif.S` with type equations. For instance `type 'a t = (module Digestif.S with type t = 'a)` doesn't work if  the type `t` is not abstract (I actually have that issue with Irmin). You also gain forward compatibility, as you could change the type `t` to something else later on (and that's one of the reason I am not very confortable having so many `Obj.magic` lying around in the code).

**Comment by cfcs** [comment]
Thanks for explaining that! And yes, the `Obj.magic` should likely be eradicated...... :)

**Pull request merged**
