### PR TITLE
Use String.init intead Bytes.create in of_hex function

### PR DESCRIPTION
**Pull request by dinosaure**

### CODE REVIEW

**Comment by dinosaure** [comment]
@cfcs good for you?

**Comment by cfcs** [comment]
@dinosaure looks good, but was I think you left out `'\n'` by accident (not much point in ignoring `'\r'` if you don't accept `'\n'`)?

**Comment by cfcs** [comment]
Btw, this implementation silently ignores anything after `D.digest_size`, is that documented in the mli?

**Comment by dinosaure** [comment]
I will document it in another PR.

**Comment by cfcs** [comment]
LGTM :tada:

**Pull request merged**
