### PR TITLE
Fix linking problem both definition of src/* modules

### PR DESCRIPTION
**Pull request by dinosaure**

### CODE REVIEW

**Comment by g2p** [comment]
```

#=== ERROR while compiling git.dev ============================================#
# context     2.0.0 | linux/x86_64 | ocaml-variants.4.07.1+fp+flambda | pinned(file:///home/g2p/src/storage-unikernel/vendor/ocaml-git)
# path        ~/.opam/4.07.1+fp+flambda/.opam-switch/build/git.dev
# command     ~/.opam/opam-init/hooks/sandbox.sh build dune build -p git -j 3
# exit-code   1
# env-file    ~/.opam/log/git-27269-457407.env
# output-file ~/.opam/log/git-27269-457407.out
### output ###
#       ocamlc src/git/.git.objs/git__S.{cmi,cmo,cmt} (exit 2)
# (cd _build/default && /home/g2p/.opam/4.07.1+fp+flambda/bin/ocamlc.opt -w -40 -g -bin-annot -I src/git/.git.objs -I src/git/.git.objs/.private -I /home/g2p/.opam/4.07.1+fp+flambda/lib/angstrom -I /home/g2p/.opam/4.07.1+fp+flambda/lib/astring -I /home/g2p/.opam/4.07.1+fp+flambda/lib/bigstringaf -I /home/g2p/.opam/4.07.1+fp+flambda/lib/bytes -I /home/g2p/.opam/4.07.1+fp+flambda/lib/checkseum -I[...]
# File "src/git/s.ml", line 131, characters 10-20:
# Error: Unbound module Digestif
# Hint: Did you mean Digest?
```
[git-27269-457407.out.txt](https://github.com/mirage/digestif/files/2460668/git-27269-457407.out.txt)

**Comment by g2p** [comment]
Works for me!

**Comment by dinosaure** [comment]
@rgrinberg this fix seems close to what `dune` should does on _variant_ package. I mean, the first problem seems a duplication of symbols on `src/digestif.a` with `src-c/digestif.a` and `src-ocaml/digestif.a`. I just avoid it and replace `%{lib:src:digestif_*.ml}` by `../src/digestif_*.ml` on `dune` files to produce implementation.

Then, I precise to `dune` to use the _fake_ module `Digestif` on `src/dune` to avoid a linking error noticed by @g2p on `ocaml-git`.

Finally, I really don't know what I did but it seems to work. However. I don't want to break linking assumptions on `digestif` at this point. So, if you can confirm than this is the good way, I will happy to merge it.

I don't know what I'm doing

**Comment by dinosaure** [comment]
Seems fine in the situation of `dune`/`ocamlfind`/`META` file and /unikernel/. See #75

**Pull request closed without merging**
